@startuml TrackyCloudSequence
title Tracky

actor User as U
actor Admin as ADM

participant "Mobile App" as MA
participant "User Service" as US
participant "Notification Service" as NS
participant "Campaign Service" as CS

participant "Database" as DB
participant "RabbitMQ" as RMQ

participant "FCM (Push Notifications)" as FCM
participant "Email Service (Email)" as ES

== Campaigns ==

ADM -> CS: Triggers a campaign, providing\nmessage and user type
activate CS
CS -> US: GET /users?type={DRIVER or CUSTOMER}
US --> CS: List of users
loop users matched
CS -> RMQ: Publishes a notification request\nwith device token, email and message
RMQ -> NS: Triggers a notification
activate NS
NS -> FCM: Send push notification
FCM -> MA: Send push notification
MA -> U: Displays the notification
NS -> ES: Send email notification
ES -> U: Notifies the user
deactivate NS
end
CS -> DB: Register campaign with number of users reached
deactivate CS

@enduml