@startuml TrackyCloudSequence
title Tracky

actor Driver as D
actor Customer as C

participant "Mobile App" as MA
participant "User Service" as US
participant "Order Service" as OS
participant "Notification Service" as NS

participant "Database" as DB
participant "RabbitMQ" as RMQ

participant "FCM (Push Notifications)" as FCM
participant "Email Server" as ES

== Order Delivered Notification ==

D -> MA: Driver confirms delivery
MA -> OS: Driver confirms delivery

activate OS
OS -> DB: Update order status to delivered
OS -> RMQ: Publishes order delivered event
deactivate OS

RMQ -> NS: Triggers order delivered notification

activate NS
NS -> FCM: Send push notification to customer
FCM -> C: Send push notification
NS -> ES: Send email notification to customer
ES -> C: Notifies the customer
NS -> ES: Send email notification to driver
ES -> D: Notifies the driver

NS -> DB: Register notification for audit purposes
deactivate NS

@enduml