server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://tracking-db:5432/trackingdb
    username: trackingservice
    password: trackingpass123
    driver-class-name: org.postgresql.Driver

eureka:
  instance:
    hostname: tracking-service
