server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://user-db:5432/userdb
    username: userservice
    password: userpass123
    driver-class-name: org.postgresql.Driver

jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: 86400000 # 24 hours

eureka:
  instance:
    hostname: user-service
