spring:
  application:
    name: notification-service
  profiles:
    active: local
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: notification-service
        instance-id: ${spring.application.name}:${server.port}
        health-check-path: /actuator/health
        health-check-interval: 15s

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5435/notificationdb
    username: notificationservice
    password: ${NOTIFICATION_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: tracky
    password: ${RABBITMQ_PASSWORD}
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:your-email@gmail.com}
    password: ${SMTP_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8084

app:
  rabbitmq:
    exchange: tracky.exchange
    queue:
      order-delivered: order.delivered.queue
    routing-key:
      order-delivered: order.delivered
  fcm:
    server-key: ${FCM_SERVER_KEY:your-fcm-server-key-here}

logging:
  level:
    com.tracky.notificationservice: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    consul:
      host: ${CONSUL_HOST:consul}
      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: notification-service
        instance-id: ${spring.application.name}:${server.port}
        health-check-path: /actuator/health
        health-check-interval: 15s
        hostname: notification-service
        prefer-ip-address: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:notification-db}:${DB_PORT:5432}/${DB_NAME:notificationdb}
    username: ${DB_USERNAME:notificationservice}
    password: ${DB_PASSWORD:${NOTIFICATION_DB_PASSWORD}}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:tracky}
    password: ${RABBITMQ_PASSWORD:${RABBITMQ_PASSWORD}}
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:your-email@gmail.com}
    password: ${SMTP_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8084

app:
  rabbitmq:
    exchange: tracky.exchange
    queue:
      order-delivered: order.delivered.queue
    routing-key:
      order-delivered: order.delivered
  fcm:
    server-key: ${FCM_SERVER_KEY:your-fcm-server-key-here}

logging:
  level:
    com.tracky.notificationservice: INFO
