// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvI9vfbiXAZyKyPnCO2JuV8kN_TeBbiR4',
    appId: '1:173484730276:web:10c1a818ec57244b11c331',
    messagingSenderId: '173484730276',
    projectId: 'my-cloud-tracky-project',
    authDomain: 'my-cloud-tracky-project.firebaseapp.com',
    storageBucket: 'my-cloud-tracky-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPg7ztLQ5J0uhTOl0gko-2DbHGECKVB2A',
    appId: '1:173484730276:android:709abe18e09ceaf911c331',
    messagingSenderId: '173484730276',
    projectId: 'my-cloud-tracky-project',
    storageBucket: 'my-cloud-tracky-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7YejOVnUMe7wQdhvPVA484FLidfxOm98',
    appId: '1:173484730276:ios:a9e6a788eb9b527d11c331',
    messagingSenderId: '173484730276',
    projectId: 'my-cloud-tracky-project',
    storageBucket: 'my-cloud-tracky-project.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7YejOVnUMe7wQdhvPVA484FLidfxOm98',
    appId: '1:173484730276:ios:a9e6a788eb9b527d11c331',
    messagingSenderId: '173484730276',
    projectId: 'my-cloud-tracky-project',
    storageBucket: 'my-cloud-tracky-project.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvI9vfbiXAZyKyPnCO2JuV8kN_TeBbiR4',
    appId: '1:173484730276:web:2083d3ffe208f27911c331',
    messagingSenderId: '173484730276',
    projectId: 'my-cloud-tracky-project',
    authDomain: 'my-cloud-tracky-project.firebaseapp.com',
    storageBucket: 'my-cloud-tracky-project.firebasestorage.app',
  );
}
